export const FETCH_LATEST_INCIDENT_STARTED = 'FETCH_LATEST_INCIDENT_STARTED';
export const INCIDENT_FETCH_SUCCEEDED = 'INCIDENT_FETCH_SUCCEEDED';
export const URL_INCIDENT_TABLE =
  'api/now/table/incident?sysparm_display_value=true';
export const DROPDOWN_PANEL_ITEM_CLICKED = 'NOW_DROPDOWN_PANEL#ITEM_CLICKED';
export const INCIDENT_CARD_SELECTED = 'NOW_TEMPLATE_CARD_ASSIST#SELECTED_SET';
export const INCIDENT_DELETE_STARTED = 'INCIDENT_DELETE_STARTED';
export const URL_INCIDENT_DELETED = 'api/now/table/incident/:sys_id';
export const INCIDENT_CARD_OPENED = 'INCIDENT_CARD_OPENED';
export const MODAL_DISMISSED = 'NOW_MODAL#OPENED_SET';
export const INCIDENT_CARD_CLOSED = 'INCIDENT_CARD_CLOSED';
export const INCIDENT_DELETE_SUCCEEDED = 'INCIDENT_DELETE_SUCCEEDED';
export const MODAL_DELETE_BUTTON_CLICKED = 'NOW_MODAL#FOOTER_ACTION_CLICKED';
export const RADIO_BUTTON_SET = 'NOW_RADIO_BUTTONS#VALUE_SET';
export const INPUT_FIELD_SET = 'NOW_INPUT#INPUT';
export const FILTER_STARTED = 'FILTER_STARTED';
export const FILTER_SUCCEEDED = 'FILTER_SUCCEEDED';
export const INCIDENTS_FILTER_STARTED = 'INCIDENTS_FILTER_STARTED';
export const INCIDENTS_FILTER_FAILED = 'INCIDENTS_FILTER_FAILED';

export const nowCardActionsId = {
  open: 'open',
  delete: 'delete',
};
